version: "3.9"

services:
  db:
    image: postgres:16
    container_name: proximity_db
    #restart: always
    environment:
      POSTGRES_USER: vlad
      POSTGRES_PASSWORD: vlad123
      POSTGRES_DB: proximity_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db10k:
    image: postgres:16
    container_name: proximity_db10k
    #restart: always
    environment:
      POSTGRES_USER: vlad
      POSTGRES_PASSWORD: vlad123
      POSTGRES_DB: proximity_db10k
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_10k:/var/lib/postgresql/data

  db1k:
    image: postgres:16
    container_name: proximity_db1k
    #restart: always
    environment:
      POSTGRES_USER: vlad
      POSTGRES_PASSWORD: vlad123
      POSTGRES_DB: proximity_db1k
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_1k:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: proximity_redis
    #restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]  #this helps with volume persistence
  
  redis_10k:
    image: redis:7
    container_name: proximity_redis_10k
    #restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data_10k:/data
    command: ["redis-server", "--appendonly", "yes"]  #this helps with volume persistence

  redis_1k:
    image: redis:7
    container_name: proximity_redis_1k
    #restart: always
    ports:
      - "6381:6379"
    volumes:
      - redis_data_1k:/data
    command: ["redis-server", "--appendonly", "yes"]  #this helps with volume persistence

  web:
    build: .
    container_name: proximity_web
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - db10k
      - redis_10k
      - db1k
      - redis_1k

volumes:
  postgres_data:
  postgres_data_10k:
  postgres_data_1k:
  redis_data:
  redis_data_10k:
  redis_data_1k: